# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import enum
import typing

from nautilus_trader import model
from nautilus_trader import network

__all__ = [
    "ALPACA",
    "ALPACA_CLIENT_ID",
    "ALPACA_VENUE",
    "AlpacaAccountActivityClient",
    "AlpacaBarAdjustment",
    "AlpacaDataClientConfig",
    "AlpacaDataClientFactory",
    "AlpacaDataEnvironment",
    "AlpacaDataFeed",
    "AlpacaEnvironment",
    "AlpacaExecutionClientConfig",
    "AlpacaExecutionClientFactory",
    "AlpacaHistoricalDataClient",
    "AlpacaPortfolioClient",
    "AlpacaReferenceDataClient",
]

ALPACA: str
ALPACA_CLIENT_ID: model.ClientId
ALPACA_VENUE: model.Venue

@typing.final
class AlpacaAccountActivityClient:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        environment: AlpacaEnvironment = ...,
        base_url: str | None = None,
        timeout_secs: int = 10,
        max_retries: int = 3,
        proxy_url: str | None = None,
    ) -> None: ...
    def get_activities(
        self,
        activity_type: str,
        start: str | None = None,
        end: str | None = None,
        order_id: str | None = None,
        page_token: str | None = None,
        page_size: int = 100,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_all_activities(
        self,
        activity_type: str,
        start: str | None = None,
        end: str | None = None,
        order_id: str | None = None,
        max_items: int = 10000,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_fills(
        self,
        start: str | None = None,
        end: str | None = None,
        order_id: str | None = None,
        max_items: int = 10000,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...

@typing.final
class AlpacaDataClientConfig:
    @property
    def base_url_data_http(self) -> str | None: ...
    @property
    def base_url_trading_http(self) -> str | None: ...
    @property
    def base_url_data_ws(self) -> str | None: ...
    @property
    def instrument_ids(self) -> list[model.InstrumentId] | None: ...
    @property
    def data_environment(self) -> AlpacaDataEnvironment: ...
    @property
    def trading_environment(self) -> AlpacaEnvironment: ...
    @property
    def feed(self) -> AlpacaDataFeed: ...
    @property
    def historical_feed(self) -> AlpacaDataFeed | None: ...
    @property
    def bar_adjustment(self) -> AlpacaBarAdjustment: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def http_max_retries(self) -> int: ...
    @property
    def transport_backend(self) -> network.TransportBackend: ...
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_data_http: str | None = None,
        base_url_trading_http: str | None = None,
        base_url_data_ws: str | None = None,
        proxy_url: str | None = None,
        instrument_ids: typing.Sequence[model.InstrumentId] | None = None,
        data_environment: AlpacaDataEnvironment | None = None,
        trading_environment: AlpacaEnvironment | None = None,
        feed: AlpacaDataFeed | None = None,
        historical_feed: AlpacaDataFeed | None = None,
        bar_adjustment: AlpacaBarAdjustment | None = None,
        http_timeout_secs: int | None = None,
        http_max_retries: int | None = None,
        transport_backend: network.TransportBackend | None = None,
    ) -> None: ...
    @property
    def has_credentials(self) -> bool: ...
    @property
    def has_proxy_url(self) -> bool: ...
    def validate(self) -> None: ...

@typing.final
class AlpacaDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class AlpacaExecutionClientConfig:
    @property
    def account_id(self) -> model.AccountId: ...
    @property
    def base_url_trading_http(self) -> str | None: ...
    @property
    def base_url_trading_ws(self) -> str | None: ...
    @property
    def environment(self) -> AlpacaEnvironment: ...
    @property
    def account_type(self) -> model.AccountType: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def http_max_retries(self) -> int: ...
    @property
    def extended_hours(self) -> bool: ...
    @property
    def transport_backend(self) -> network.TransportBackend: ...
    def __init__(
        self,
        account_id: model.AccountId | None = None,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_trading_http: str | None = None,
        base_url_trading_ws: str | None = None,
        proxy_url: str | None = None,
        environment: AlpacaEnvironment | None = None,
        account_type: model.AccountType | None = None,
        http_timeout_secs: int | None = None,
        http_max_retries: int | None = None,
        extended_hours: bool | None = None,
        transport_backend: network.TransportBackend | None = None,
    ) -> None: ...
    @property
    def has_credentials(self) -> bool: ...
    @property
    def has_proxy_url(self) -> bool: ...
    def validate(self) -> None: ...

@typing.final
class AlpacaExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class AlpacaHistoricalDataClient:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url: str | None = None,
        timeout_secs: int = 10,
        max_retries: int = 3,
        proxy_url: str | None = None,
    ) -> None: ...
    def get_snapshot(
        self, symbol: str, feed: AlpacaDataFeed = ...
    ) -> typing.Awaitable[dict[str, object]]: ...
    def get_snapshots(
        self, symbols: typing.Sequence[str], feed: AlpacaDataFeed = ...
    ) -> typing.Awaitable[dict[str, dict[str, object]]]: ...
    def get_option_chain(
        self,
        underlying_symbol: str,
        feed: str,
        option_type: str | None = None,
        strike_price_gte: str | None = None,
        strike_price_lte: str | None = None,
        expiration_date: str | None = None,
        expiration_date_gte: str | None = None,
        expiration_date_lte: str | None = None,
        root_symbol: str | None = None,
        updated_since: str | None = None,
        max_items: int = 1000,
    ) -> typing.Awaitable[dict[str, dict[str, object]]]: ...
    def get_option_snapshots(
        self,
        symbols: typing.Sequence[str],
        feed: str,
        updated_since: str | None = None,
        max_items: int = 100,
    ) -> typing.Awaitable[dict[str, dict[str, object]]]: ...
    def get_option_bars(
        self,
        symbols: typing.Sequence[str],
        timeframe: str,
        start: str,
        end: str,
        max_items: int = 100000,
    ) -> typing.Awaitable[dict[str, list[dict[str, object]]]]: ...
    def get_option_trades(
        self, symbols: typing.Sequence[str], start: str, end: str, max_items: int = 100000
    ) -> typing.Awaitable[dict[str, list[dict[str, object]]]]: ...
    def get_most_actives(
        self, by: str = "volume", top: int = 10
    ) -> typing.Awaitable[dict[str, object]]: ...
    def get_market_movers(self, top: int = 10) -> typing.Awaitable[dict[str, object]]: ...
    def get_exchange_codes(self) -> typing.Awaitable[dict[str, str]]: ...
    def get_condition_codes(
        self, tick_type: str, tape: str
    ) -> typing.Awaitable[dict[str, str]]: ...
    def get_bars(
        self,
        symbol: str,
        timeframe: str,
        start: str,
        end: str,
        feed: AlpacaDataFeed = ...,
        adjustment: AlpacaBarAdjustment = ...,
        max_items: int = 10000,
        asof: str | None = None,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_trades(
        self,
        symbol: str,
        start: str,
        end: str,
        feed: AlpacaDataFeed = ...,
        max_items: int = 10000,
        asof: str | None = None,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_quotes(
        self,
        symbol: str,
        start: str,
        end: str,
        feed: AlpacaDataFeed = ...,
        max_items: int = 10000,
        asof: str | None = None,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_bars_multi(
        self,
        symbols: typing.Sequence[str],
        timeframe: str,
        start: str,
        end: str,
        feed: AlpacaDataFeed = ...,
        adjustment: AlpacaBarAdjustment = ...,
        max_items: int = 100000,
        asof: str | None = None,
    ) -> typing.Awaitable[dict[str, list[dict[str, object]]]]: ...
    def get_trades_multi(
        self,
        symbols: typing.Sequence[str],
        start: str,
        end: str,
        feed: AlpacaDataFeed = ...,
        max_items: int = 100000,
        asof: str | None = None,
    ) -> typing.Awaitable[dict[str, list[dict[str, object]]]]: ...
    def get_quotes_multi(
        self,
        symbols: typing.Sequence[str],
        start: str,
        end: str,
        feed: AlpacaDataFeed = ...,
        max_items: int = 100000,
        asof: str | None = None,
    ) -> typing.Awaitable[dict[str, list[dict[str, object]]]]: ...
    def get_auctions(
        self,
        symbols: typing.Sequence[str],
        start: str,
        end: str,
        max_items: int = 100000,
        asof: str | None = None,
    ) -> typing.Awaitable[dict[str, list[dict[str, object]]]]: ...
    def get_news(
        self,
        symbols: str | None = None,
        start: str | None = None,
        end: str | None = None,
        sort: str = "desc",
        include_content: bool = False,
        exclude_contentless: bool = False,
        max_items: int = 1000,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_corporate_actions(
        self,
        symbols: str | None = None,
        cusips: str | None = None,
        action_types: str | None = None,
        start: str | None = None,
        end: str | None = None,
        ids: str | None = None,
        region: str | None = None,
        data_quality: str | None = None,
        sort: str = "asc",
        max_items: int = 10000,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...

@typing.final
class AlpacaPortfolioClient:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        environment: AlpacaEnvironment = ...,
        base_url: str | None = None,
        timeout_secs: int = 10,
        max_retries: int = 3,
        proxy_url: str | None = None,
    ) -> None: ...
    def get_account(self) -> typing.Awaitable[dict[str, object]]: ...
    def get_positions(self) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_portfolio_history(
        self,
        period: str | None,
        timeframe: str | None,
        start: str | None,
        end: str | None,
        intraday_reporting: str,
        cashflow_types: str | None = None,
    ) -> typing.Awaitable[dict[str, object]]: ...
    def get_market_clock(self) -> typing.Awaitable[dict[str, object]]: ...
    def get_calendar(
        self, start: str | None = None, end: str | None = None
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_orders(
        self,
        status: str = "open",
        symbols: str | None = None,
        after: str | None = None,
        until: str | None = None,
        nested: bool = True,
        max_items: int = 10000,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_order(
        self, order_id: str, nested: bool = True
    ) -> typing.Awaitable[dict[str, object]]: ...
    def get_order_by_client_order_id(
        self, client_order_id: str
    ) -> typing.Awaitable[dict[str, object]]: ...

@typing.final
class AlpacaReferenceDataClient:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        environment: AlpacaEnvironment = ...,
        base_url: str | None = None,
        timeout_secs: int = 10,
        max_retries: int = 3,
        proxy_url: str | None = None,
    ) -> None: ...
    def get_asset(self, symbol_or_asset_id: str) -> typing.Awaitable[dict[str, object]]: ...
    def get_assets(
        self,
        status: str,
        exchange: str | None = None,
        attributes: typing.Sequence[str] | None = None,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_option_contract(
        self, symbol_or_contract_id: str
    ) -> typing.Awaitable[dict[str, object]]: ...
    def get_option_contracts(
        self,
        underlying_symbols: typing.Sequence[str] | None,
        status: str,
        option_type: str | None = None,
        style: str | None = None,
        expiration_date: str | None = None,
        expiration_date_gte: str | None = None,
        expiration_date_lte: str | None = None,
        root_symbol: str | None = None,
        strike_price_gte: str | None = None,
        strike_price_lte: str | None = None,
        show_deliverables: bool = False,
        ppind: bool | None = None,
        max_items: int = 10000,
    ) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_watchlists(self) -> typing.Awaitable[list[dict[str, object]]]: ...
    def get_watchlist(self, watchlist_id: str) -> typing.Awaitable[dict[str, object]]: ...
    def get_watchlist_by_name(self, name: str) -> typing.Awaitable[dict[str, object]]: ...

@typing.final
class AlpacaBarAdjustment(enum.Enum):
    RAW = ...
    SPLIT = ...
    DIVIDEND = ...
    ALL = ...

    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def name(self) -> str: ...
    def value(self) -> int: ...

@typing.final
class AlpacaDataEnvironment(enum.Enum):
    LIVE = ...
    SANDBOX = ...

    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def name(self) -> str: ...
    def value(self) -> int: ...

@typing.final
class AlpacaDataFeed(enum.Enum):
    IEX = ...
    SIP = ...
    DELAYED_SIP = ...
    BOATS = ...
    OVERNIGHT = ...
    OTC = ...

    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def name(self) -> str: ...
    def value(self) -> int: ...

@typing.final
class AlpacaEnvironment(enum.Enum):
    LIVE = ...
    PAPER = ...

    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def name(self) -> str: ...
    def value(self) -> int: ...
